### ISSUE TITLE
ltsgraph has minor problems

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1517]
Ltsgraph does not show a picture initially on a mac (problem started with MacOs Mojave).
The picture is only drawn after resizing the window manually. 
It moreover sometimes crashes when it is terminated by pressing the red closing button. It also
crashes when giving the quit command.

**Comment by Valo13** [comment]
I can confirm that the crashing of ltsgraph on exit also occurs on Windows 10 when the toolset is built using Visual studio 2017 and Qt 5.9. I did not have this issue when I used Visual studio 2015 and Qt 5.6.

**Comment by jgroote** [comment]
This problem seems to be dependent on the use of Qt 5.12.0. Problems with showing graphics on the screen dissappear with version Qt 5.12.1. I add a warning to the webpage. 

The termination problem is not yet resolved by using this new version.

**Comment by jgroote** [comment]
The termination problem is not resolved. It is not a service if the system automatically closes an issue, when I explicitly write "partly resolves"....

**Comment by jgroote** [comment]
Resolved by outcommenting a delete. See commit feac8d9ac9cef30643c76dcce36651a41f6c35f2.

**Comment by Valo13** [comment]
The termination crash still exists on my end. One thing to note though is that this crash only occurs when an lts was opened. When I start ltsgraph without opening an lts and then close it the crash does not occur.

**Comment by Valo13** [comment]
The above commit fixes the issue on my end, could you check whether it is resolved on Mac too?

**Comment by mlaveaux** [comment]
Surprisingly, deleting the m_application using delete did also not clean up the resources used by MainWindow properly. Therefore, the above commit ensures that the MainWindow object is explicitly deleted before the QApplication object. This seems to resolve the issues with ltsgraph locally.  Furthermore, the destructor of FileBrowser (which was not called before) freed objects twice was has also been fixed.

**Comment by mlaveaux** [comment]
This issue has been resolved under all tested systems (Linux, Mac and Windows) by noting in our documentation that Qt 12.0 is broken (at least under Mac) and by cleaning up the MainWindow properly.
